name: Test workflow
on: 
  push:
    branches:
     - main
  pull_repquest:
    bransches:
      - main
jobs:
   testjob:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello Worls"
        shell: bash
