name: Test workflow
on: 
  workflow_dispatch:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main
jobs:
   testjob:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Say hello
        run: echo "Hello World"
        shell: bash
